### ISSUE TITLE
laad geen tabellen

### ISSUE THREAD

**Issue by indexample** [jeroenterheerdt/PowerBI-CBS-OpenData#1]
bij het navigeren (thema onderwijs) en het aanklikken van Middelbaar beroepsonderwijs blijft het navigatiescherm hangen/laden. er wordt geen preview getoond. 

(powerbi desktop juli 2017)

**Comment by jeroenterheerdt** [comment]
Er zijn wat wijzigingen geweest in de API van CBS Statline, ik werk aan een nieuwe versie.
