### ISSUE TITLE
Zeer traag tot niet werkend

### ISSUE THREAD

**Issue by taimus** [jeroenterheerdt/PowerBI-CBS-OpenData#2]
Zeer mooi als dit gaat werken, maar werkt nu nog niet.
Ik zie wel de tabellen (als ik b.v. zoek op arbeid), maar als ik door klik op een tabel blijft PowerBI zeer lang laden (ik stop het maar na 10 minuten).  
Bekend probleem?

**Comment by jeroenterheerdt** [comment]
Ja, bekend probleem - de CBS statline website is supertraag via de publieke, niet betaalde API die ik gebruik.
